server:
  port: 8081
#  servlet:
#    context-path: /vincent

spring:
  profiles:
    active: jdbc

  devtools:
    restart:
      enabled: true

  thymeleaf:
#    prefix: classpath:/templates/
#    heck-template-location: true
#    suffix: .html
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
    mode: HTML5
    cache: false
#    enable-spring-el-compiler: false
#
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#    static-path-pattern: classpath:/static/
#
#  resources:
#    static-locations: classpath:/static/
#  mvc:
#    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static/**
#
#  resources:
#      add-mappings: false

mybatis:
  type-aliases-package: com.vincent.personal.dao


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#httpportcfg:
#  http_port: 8080
#  https_port: 8443
#
## Nettyserver \u914D\u7F6E
#nettyserver:
#  serviceIp: 0.0.0.0
#  servicePort: 3460
